### ISSUE TITLE
reuse existing comment instead of recreating a new one

### ISSUE THREAD

**Issue by moul** [snyk/release-notes-preview#27]
Hi, I love the idea behind this action. However, it's unusable (too much spam, and not so much relevant) when your workflow consists of adding more commits, squashing the commits, etc;. as soon as your workflow is different from "pushing only 1 commit"

What do you think about adding an option (can be opt-it) to either update existing comments or cleaning the old ones?

thank you

**Comment by Shesekino** [comment]
Hey @moul , thanks for the review :)
The current behaviour already consists of deleting the previous comments https://github.com/snyk/release-notes-preview/blob/ceb0664b8cc797c1c91b586002198bd7fa61a295/src/pull-request.ts#L10
if it does not work, then it's a bug. However, I do see it working well in different repositories.

I noticed that GitHub needs to refresh the page in order for deleted comments to be "unseen", while no page refresh is needed for new comments to be seen. Could that be the issue? (Just refreshing the page).

Otherwise I may need to see an existing example of reproducing this problem to have a better sense of what's going on.

How does that sound?

Thanks!

**Comment by moul** [comment]
@Shesekino ok, thank you for your message

I will share here an example the next time it happens

**Comment by Shesekino** [comment]
great :) leaving the issue open for now. thanks!

**Comment by moul** [comment]
I was trying to reproduce the bug on a clean repo and hit another issue -> https://github.com/moul/test/runs/838502782?check_suite_focus=true

**Comment by moul** [comment]
I made some tests -> https://github.com/moul/test/pull/5

I can't reproduce the bug, I think you're right and I only needed to hit refresh on my browser to see the older ones disappear

Feel free to close this issue, if I really have a similar problem persisting I will reopen

**Comment by Shesekino** [comment]
Sure thing, thanks a lot for our involvement and engagement :) I appreciate it.
